create extension pgcrypto;

create unique index username on users(username);

create table users (
id int generated by default as identity primary key,
firstname character varying(32) not null,
lastname character varying(32) not null,
password character varying(60) not null,
username character varying(32) not null,
joined_at timestamp with time zone default current_timestamp
);



create table conversations (
  conversation_id int generated by default as identity primary key,
  created_at timestamp with time zone default current_timestamp,
  sender_id int not null references users(id),
  receiver_id int not null references users(id)
);

create table messages (
message_id int generated by default as identity primary key,
content text not null,
is_read boolean default false,
created_at timestamp with time zone default current_timestamp,
sender_id int not null references users(id),
conversation_id int not null references conversations(conversation_id)
);

insert into users (firstname, lastname, username, password) values ('begzod', 'begzod', 'begzod', crypt('1234', gen_salt('bf')));

-- create table tweets (
-- 	tweet_id int4 generated by default as identity primary key,
-- 	type int2 default 0,
-- 	content character varying(256) not null,
-- 	created_at timestamp with time zone default current_timestamp,
-- 	user_id int4 not null references users (user_id)
-- );
